name: Quiz Workflow

on:
  push:
    branches:
      - main
    paths:
      - 'data/*.json'
      - '.github/workflows/*.yml'
      - 'Dockerfile'
      - 'api/**'
      - 'js/**'
      - 'index.html'

  workflow_dispatch:

jobs:
  update-index:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout repo with full history
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install jq
      run: sudo apt-get install jq

    - name: Vérification token et repo
      run: |
        echo "Repo : ${{ github.repository }}"
        echo "Token présent : ${{ secrets.GH_PAT != '' }}"

    - name: Run index update script
      run: |
        echo "Diff entre ${{ github.event.before }} et ${{ github.sha }}"
        git diff --name-only ${{ github.event.before }} ${{ github.sha }}

        NEW_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- 'data/*.json' | grep -v index.json || true)

        echo "Nouveaux fichiers détectés : $NEW_FILES"

        for file in $NEW_FILES; do
          echo "Traitement de $file"
          TITLE=$(jq -e -r .titre "$file" 2>/dev/null || echo "")
          if [ -z "$TITLE" ]; then
            echo "⚠️  Le fichier $file ne contient pas de champ .titre. Ignoré."
            continue
          fi

          BASENAME=$(basename "$file")

          if ! jq -e --arg f "$BASENAME" '.[] | select(.fichier == $f)' data/index.json > /dev/null; then
            echo "Ajout de $file ($TITLE) à index.json"
            TMP=$(mktemp)
            jq --arg t "$TITLE" --arg f "$BASENAME" '. += [{"titre": $t, "fichier": $f}]' data/index.json > "$TMP"
            mv "$TMP" data/index.json
          else
            echo "$file est déjà dans index.json"
          fi
        done

    - name: Commit and push if index changed
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add data/index.json
        git diff --cached --quiet || git commit -m "Mise à jour automatique de l'index des quiz"
        git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git

  deploy:
    needs: update-index
    runs-on: ubuntu-latest

deploy:
  needs: update-index
  runs-on: ubuntu-latest

  steps:
    - name: Trigger Render Deployment
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        serviceId: ${{ secrets.RENDER_SERVICE_ID }}
        apiKey: ${{ secrets.RENDER_API_KEY }}
